### ISSUE TITLE
Storage Manager implementation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-nodejs#12]
As discussed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/119)

**Comment by jboulmal** [comment]
We have implemented `Dexie` with [IndexeDBshim](https://github.com/axemclion/IndexedDBShim), It seems to respond correctly. However, we have got a blocking error, we can't close this issue unless  this one [core-runtime](https://github.com/reTHINK-project/dev-runtime-core/issues/131) is resolved due to last update on develop branch of `#runtime-core`.

**Comment by jboulmal** [comment]
Ongoing here https://github.com/reTHINK-project/dev-runtime-core/issues/131

**Comment by jboulmal** [comment]
Here https://github.com/reTHINK-project/dev-runtime-nodejs/blob/develop/src/RuntimeFactory.js#L29
